version: '3.1'

services:
  tb-bot:
    depends_on:
      - tb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  tb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DFTABASE: 'tb-db'
      MYSQL_ROOT_PASSWORD: '2145n24s21518953SaT!'
    ports:
      - '3306:3306'
    expose:
      - '3306'